SportsPro/Controllers/CustomerProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportsPro.Models;
using SportsPro.Models.DataLayer;
using SportsPro.Models.DomainModels;

namespace SportsPro.Controllers
{
    //Controller for a many to many customer-product table
    [Authorize(Roles = "Admin")]
    public class CustomerProductController : Controller
    {
        private SportProUnitOfWork data { get; set; }
        public CustomerProductController(SportsProContext ctx) => data = new SportProUnitOfWork(ctx);

        //Get method for customers
        public IActionResult getcustomer()
        {
            var customerOptions = new QueryOptions<Customer> { };
            customerOptions.OrderBy = g => g.FirstName;
            var customers = new CustomerProductViewModel
            {
                Customers = data.Customers.List(customerOptions).ToList(),
                CurrentCustomer = new Customer()
            };
            ViewBag.Current = new Customer();

            return View(customers);
        }

        //Get method for the list view
        [HttpGet]
        public IActionResult listget(int id)
        {
            var productOptions = new QueryOptions<CustomerProduct>
            {
                Includes = "Customer, Product",

            };
            productOptions.Where = g => g.CustomerId == id;

            var pOptions = new QueryOptions<Product> { };
            pOptions.OrderBy = g => g.Name;


            var cOption = new QueryOptions<Customer> { };
            cOption.Where = g => g.CustomerID == id;


            var products = new CustomerProductViewModel
            {
                CustomerProducts = data.CustomerProducts.List(productOptions).ToList(),
                Products = data.Products.List(pOptions).ToList(),
                CurrentCustomer=data.Customers.Get(cOption)
            };

            ViewBag.Current = data.Customers.Get(cOption).FullName; 


            return View("list", products);
        }

        //Post method for the list view
        [HttpPost]
        public IActionResult list(CustomerProductViewModel prod)
        {
            var productOptions = new QueryOptions<CustomerProduct>
            {
                Includes = "Customer, Product",

            };
            productOptions.Where = g => g.CustomerId == prod.CurrentCustomer.CustomerID;

            var pOptions = new QueryOptions<Product> { };
            pOptions.OrderBy = g => g.Name;
            var products = new CustomerProductViewModel {
                CustomerProducts = data.CustomerProducts.List(productOptions).ToList(),
                Products = data.Products.List(pOptions).ToList()
            };
           
            var cOption= new QueryOptions<Customer> { };
            cOption.Where = g=> g.CustomerID== prod.CurrentCustomer.CustomerID;
            ViewBag.Current = data.Customers.Get(cOption).FullName;


            return View(products);
        }

        //Post method redirecting to the listget method
        [HttpPost]
        public RedirectToActionResult Add(CustomerProductViewModel customerproduct)
        {
            var NCustomerProduct = new CustomerProduct();
            NCustomerProduct.CustomerId = customerproduct.CurrentCustomer.CustomerID;
            NCustomerProduct.ProductId = customerproduct.CurrentProduct.ProductID;
            
            try
            {
                data.CustomerProducts.Insert(NCustomerProduct);
                data.Save();
                TempData.Clear();
            }
            catch{
                TempData["Error"] = "Please select a product that is not selected";

            }
     
            int ID = NCustomerProduct.CustomerId;
            return RedirectToAction("listget", new {id = ID } );
        }

        //Get method for the delete view
        [HttpGet]
        public IActionResult Delete(int id, int slug)
        {
            var productOptions = new QueryOptions<CustomerProduct>
            {
                Includes = "Customer, Product",

            };
            productOptions.Where = g => g.ProductId == id;
            productOptions.Where = g => g.CustomerId == slug;

            var customerproduct = new CustomerProductViewModel
            {
                CurrentCustomerProduct = data.CustomerProducts.Get(productOptions)
            };

            return View(customerproduct);
        }

        //Post method for the delete view
        [HttpPost]
        public IActionResult Delete(CustomerProductViewModel customerproduct)
        {
            int cid = customerproduct.CurrentCustomerProduct.CustomerId;
            int pid = customerproduct.CurrentCustomerProduct.ProductId;
            var deletCP = new CustomerProduct();
            deletCP = customerproduct.CurrentCustomerProduct;
            data.CustomerProducts.Delete(deletCP);
            data.Save();
            return RedirectToAction("Listget", new { id = cid }  );
        }
    }
}

SportsPro/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SportsPro.Models;


namespace SportsPro.Controllers
{
    //Home Controller
    public class HomeController : Controller
    {
        private IProductRepository productRepository;

        public HomeController(IProductRepository _repository)
        {
            this.productRepository = _repository;
        }

        //Get method for the index
        public IActionResult Index()
        {
            return View();
        }

        //Get method for the about view
        [Route("/About/")]
        public IActionResult About() => View();

        //Get method for the unit testing for the add product
        [HttpGet]
        public ViewResult Add()
        {
            ViewBag.Action = "Add";

            return View("Edit", new Product());
        }

        //Get method for the edit view
        [HttpGet]
        public ViewResult Edit(int id)
        {
            ViewBag.Action = "Edit";

            return View("Edit", new Product());
        }

        //Get method for the list view
        public ViewResult List()
        {
            ViewBag.Action = "List";
            return View("list");
        }

        //Get method for the delete view
        public ViewResult Delete()
        {
            ViewBag.Action = "Delete";
            return View("Delete");
        }
    }

}

SportsPro/Controllers/TechnicianIncidentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportsPro.Models;
using SportsPro.Models.DataLayer;

namespace SportsPro.Controllers
{
    //Technician-Incident Controller 
    [Authorize]
    public class TechnicianIncidentController : Controller
    {
        private SportProUnitOfWork data { get; set; }
        public TechnicianIncidentController(SportsProContext ctx) => data = new SportProUnitOfWork(ctx);

        //Get method for the get view
        public IActionResult get()
        {
            var technicianOptions = new QueryOptions<Technician> { };
            technicianOptions.OrderBy = g => g.Name;
            var technicians = new IncidentEditViewModel
            {
                
                Technicians = data.Technicians.List(technicianOptions).ToList(),
                CurrentTechnician = new Technician()
            };
            ViewBag.Current = new Technician();

            return View(technicians);
        }
            
        //Post method for the list view
        [HttpPost]
        public IActionResult list(IncidentEditViewModel inc)
        {
            var incidentOptions = new QueryOptions<Incident>
            {
                Includes = "Customer, Product, Technician",

            };
            var technicianOptions = new QueryOptions<Technician> { };
            technicianOptions.Where = g=> g.TechnicianID == inc.CurrentTechnician.TechnicianID;
            incidentOptions.Where = g => g.TechnicianID == inc.CurrentTechnician.TechnicianID;
            incidentOptions.Where = g => g.DateClosed ==null;
            var incident = new IncidentEditViewModel();
            var technician = new Technician();
            technician = data.Technicians.Get(technicianOptions);
            incident.Incidents = data.Incidents.List(incidentOptions).ToList();
            ViewBag.Current = technician.Name;
            return View(incident);
        }

        //Get method for the edit view
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var customerOptions = new QueryOptions<Customer> { };
            customerOptions.OrderBy = g => g.FirstName;
            var productOptions = new QueryOptions<Product> { };
            productOptions.OrderBy = g => g.Name;
            var technicianOptions = new QueryOptions<Technician> { };
            technicianOptions.OrderBy = g => g.Name;

            var IncidentModel = new IncidentEditViewModel
            {
                CurrentIncident = data.Incidents.Get(id),
                Customers = data.Customers.List(customerOptions).ToList(),
                Products = data.Products.List(productOptions).ToList(),
                Technicians = data.Technicians.List(technicianOptions).ToList(),
                AddOrEdit = "Edit"
            };
         
            return View(IncidentModel);
        }

        //Post method for the list view
        [HttpPost]
        public IActionResult Edit(IncidentEditViewModel inc)
        {          
            if (inc.CurrentIncident == null)
                data.Incidents.Insert(inc.CurrentIncident);
            else
                data.Incidents.Update(inc.CurrentIncident);
            data.Save();
          
            var Id = inc.CurrentIncident.TechnicianID;
            var technician = new IncidentEditViewModel();
            technician.CurrentTechnician = data.Technicians.Get((int)Id);

            var incidentOptions = new QueryOptions<Incident>
            {
                Includes = "Customer, Product, Technician",

            };
            incidentOptions.Where = g => g.TechnicianID == technician.CurrentTechnician.TechnicianID;
            incidentOptions.Where = g => g.DateClosed == null;
            var incident = new IncidentEditViewModel();
            incident.Incidents = data.Incidents.List(incidentOptions).ToList();
            ViewBag.Current = data.Incidents.Get(incidentOptions).Technician.Name;

            return View("list", incident);        
        }
    }
}

SportsPro/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Admin";
    ViewBag.mode = "About";
}

<div class="jumbotron bg-secondary mt-4">
    <h1 class="text-light">About</h1>
    <p class="text-light">SportsPro Technical Support constantly strives to provide the highest level of technical support for all products in the SportsPro family.</p>
</div>

<div class="jumbotron bg-secondary mt-4">
    <div style="text-align:center">
        <h2 class="text-light">Contact Us</h2>
        <p class="text-light">Swing by for a cup of coffee:</p>
    </div>
    <div class="row">
        <div class="column">
            <p class="text-light">
                <strong>Address:</strong>
                <br /> 7500 MCLeod Trail SW, Calgary, Alberta
            </p>
            <p class="text-light">
                <strong>Email:</strong>
                <br /> sportspro@yahoo.com
            </p>
            <p class="text-light">
                <strong>Phone:</strong>
                <br /> (555)-567-7655
            </p>
            <p class="text-light">
                <strong>Linkedin:</strong>
                <br /> https://www.linkedin.com/company/sportspro/
            </p>
            <p class="text-light">
                <strong>Facebook:</strong>
                <br /> https://www.facebook.com/sportspro/
            </p>
        </div>
        <div class="column">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2511.614010717529!2d-114.07366048471305!3d50.98632485648883!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5371711d460ee7c5%3A0x8fc90691b851f35f!2s7500%20Macleod%20Trail%20SW%2C%20Calgary%2C%20AB!5e0!3m2!1sen!2sca!4v1602007945727!5m2!1sen!2sca" width="600" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>

        </div>
    </div>
</div>

<h2 style="text-align:center">Our Team</h2>
@*<div class="row">
        <div class="column">
            <div class="card">
                <img src="~/Images/JohnSmith.png" alt="John Smith" style="width:100%">
                <div class="container">
                    <h2>John Smith</h2>
                    <p class="title">CEO & Founder</p>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="~/Images/MariaFish.jpeg" alt="Maria Fish" style="width:100%">
                <div class="container">
                    <h2>Maria Fish</h2>
                    <p class="title">Marketing Director</p>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="~/Images/BekleyDome.jpg" alt="Beckley Dome" style="width:100%">
                <div class="container">
                    <h2>Beckley Dome</h2>
                    <p class="title">Customer Relations Manager</p>
                </div>
            </div>
        </div>
    </div>*@

<div class="row">
    <div class="column">
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="~/Images/JohnSmith.png" alt="John Smith" style="width:300px">
                </div>
                <div class="flip-card-back">
                    <div class="center">
                        <h1>John Smith</h1>
                        <p>CE0 & Founder</p>
                        <p>Has over 30 years Experience as an NBA star and loves car racing </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="~/Images/MariaFish.jpeg" alt="Maria Fish" style="width:300px">
                </div>
                <div class="flip-card-back">
                    <div class="center">
                        <h1>Maria Fish</h1>
                        <p>Marketing Director</p>
                        <p>Maria loves non competitve long Tennis with over 10 years experience as a Software Developer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="~/Images/BekleyDome.jpg" alt="Bekley Dome" style="width:300px">
                </div>
                <div class="flip-card-back">
                    <div class="center">
                        <h1>Bekley Dome</h1>
                        <p>Customer Relations Manager</p>
                        <p>Has over 20 years experience handling customers, promoting business relations and handling Conflict resolutions</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SportsPro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Technicians";
    ViewBag.mode = "Home";
}

<h1>SportsPro Technical Support</h1>
<p>Sports management software for the sports enthusiast</p>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block  w-100" src="https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block  w-100" src="https://images.pexels.com/photos/3662553/pexels-photo-3662553.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block  w-100" src="https://images.pexels.com/photos/533509/pexels-photo-533509.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Third slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://images.pexels.com/photos/12801/pexels-photo-12801.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Third slide">
        </div>
        <div class="carousel-item">
            <img class="d-block  w-100" src="https://images.pexels.com/photos/3133685/pexels-photo-3133685.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<h1>Admin</h1>
<div class="container">
    <div class="row">
        <div class="col-sm pl-0">
            <a asp-controller="Product" asp-action="List"
               class="list-group-item bg-warning ">Manage Products</a>
        </div>
        <div class="col-sm">
            <a asp-controller="Technician" asp-action="List"
               class="list-group-item bg-warning">Manage Technicians</a>
        </div>
        <div class="col-sm">
            <a asp-controller="Customer" asp-action="List"
               class="list-group-item bg-warning">Manage Customers</a>
        </div>
        <div class="col-sm">
            <a asp-controller="Incident" asp-action="List"
               class="list-group-item bg-warning">Manage Incidents</a>
        </div>
        <div class="col-sm">
            <a asp-controller="CustomerProduct" asp-action="GetCustomer"
               class="list-group-item bg-warning">Man. Registrations</a>
        </div>
    </div>
</div>

<h1>Technicians</h1>
<div class="list-group ">
    <a asp-controller="TechnicianIncident" asp-action="get"
       class="list-group-item bg-warning">Update Incident</a>
</div>